### ISSUE TITLE
Publish the library to jcenter

### ISSUE THREAD

**Issue by destil** [ayltai/Android-Lib-reCAPTCHA#2]
Hi, your library looks great! But it's a hassle to integrate it to modern Gradle-based projects. Can you please publish the jar to jcenter? It's really easy.

**Comment by ayltai** [comment]
yup I'm also planning to convert projects to gradle based and have it published. I'll try to do it this week.

**Comment by ayltai** [comment]
The library is now converted to Gradle based and waiting approval to publish to jcenter .
