### ISSUE TITLE
Server Verification Support

### ISSUE THREAD

**Issue by albionh** [ayltai/Android-Lib-reCAPTCHA#4]
Hi, I am trying to use this library. However, I found out there is no support for me to verify the CAPTCHA answer on my own server. What I'm trying to do is to send the API request from my server to google and get the response. But one of the parameter to pass is the challenge which your library doesn't let me achieve it. I wonder if you can please do a little modification so I can get the challenge and pass that to my server. Or do you have a suggestion for me?

**Comment by ayltai** [comment]
Version 1.0.1 published. Now you can call `getChallenges()` after calling `showChallenge(String)` or after `OnShowChallengeListener.onChallengeShown(boolean)` is called.

`getChallenges()` returns a map of challenges in which you can get your specific challenge mapped by the corresponding public key.

**Comment by albionh** [comment]
Hi,

I think I need to access imageToken not the challenge, since you pass `this.imageToken` in the Post on line 560.
I tried the String returned by the mapping `getChallenges` but keep failing.

**Comment by ayltai** [comment]
Okay, make sense. I will also add access to imageToken as it seems imageToken and challenge could be useful in some cases.

**Comment by ayltai** [comment]
Version 1.0.2 published. The last `imageToken` and `challenge` can be accessed through `getImageToken()` and `getChallenge()` respectively.

I changed challenge map to challenge in 1.0.2 because I found that it is not useful to store a mapping of challenges and public keys when the `ImageView` can only display one image at a time.
