### ISSUE TITLE
other long-running asynctask blocks captcha display

### ISSUE THREAD

**Issue by kmthinkingrock** [ayltai/Android-Lib-reCAPTCHA#7]
I had another long-running asynctask that was preventing the captcha from being displayed - this is mostly a "newbie" issue but you  might want to mention that other incomplete asynctasks prevent the captcha from being loaded (if that is indeed the root cause - I don't know why my task is having issues). if asynctasks are serialized and process in a FIFO manner then that would explain why the captcha wasn't loading in my case. Anyway, it might help someone else in the future. Thanks so much for this!!! Super grateful for your work..

**Comment by ayltai** [comment]
Thank you for reporting. Yes the AsyncTask is queued. I will make it execute on a parallel executor.

**Comment by kmthinkingrock** [comment]
What does that do? "parallel executor? that means to have it execute right away?

**Comment by ayltai** [comment]
I plan to use [AsyncTaskCompat](https://developer.android.com/reference/android/support/v4/os/AsyncTaskCompat.html#executeParallel%28android.os.AsyncTask%3CParams,%20Progress,%20Result%3E,%20Params...%29) to manage async tasks execution.

**Comment by ayltai** [comment]
This issue is resolved in version 2.0.0.

**Comment by kmthinkingrock** [comment]
Thanks very much!
