### ISSUE TITLE
recaptcha is in french

### ISSUE THREAD

**Issue by kmthinkingrock** [ayltai/Android-Lib-reCAPTCHA#8]
my google account is set up to be in the french language, and that is the account i created my API key under. it appears that the recaptchas served by the API key I am using are always in french, even though my device is in the US English locale. Any ideas about this?

**Comment by ayltai** [comment]
The recaptcha classes don't specify a locale and Google decides to use your account locale. I will make it request to display in a configurable locale

**Comment by ayltai** [comment]
This issue is resolved in version 2.0.0.
